img_site/asciiart/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns(
   'asciiart.views', url(r'^$',TemplateView.as_view(
      template_name = 'asciiart/index.html')), url(r'^success$', 'process_image', name = 'process_image'),
   url(r'^toggle_color$', 'toggle_color', name='toggle_color')
)

img_site/img_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^', include('asciiart.urls', namespace='asciiart')),       
]

img_site/asciiart/models.py
from django.db import models

# Create your models here.

img_site/asciiart/forms.py
#-*- coding: utf-8 -*-
from django import forms

class UploadImageForm(forms.Form):
    file = forms.ImageField()

img_site/asciiart/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from forms import UploadImageForm
from django.http import HttpResponseRedirect
from transform_img import *
import sys


def toggle_color(request):
    if request.session["color"] == "white":
        request.session['display'] = request.session["display_black"]
        request.session["color"] = "black"
    else:
        request.session['display'] = request.session["display_white"]
        request.session["color"] = "white"
    # return render(request, 'asciiart/success.html')
    return HttpResponse(request.session['display'])

def process_image(request):
    if request.method == 'POST':
        form = UploadImageForm(request.POST, request.FILES)
        if form.is_valid():
            img = form.cleaned_data['file']
            tf = transformImage()
            data = tf.pre_process_img(img)
            results = tf.greyscale_to_ascii(data)  # results contain result_white and result_black
            display_white = "\n"
            display_black = "\n"
            #convert the whole array into a string to avoid re-formatting
            for row in results[0]:  # result_white
                for char in row:
                    display_white += char
                display_white += "\n"
            request.session["display_white"] = display_white  # store display_white into request session

            for row in results[1]:  # result_black
                for char in row:
                    display_black += char
                display_black += "\n"
            request.session["display_black"] = display_black # store display_black into request session

            request.session['display'] = display_white  # by default, display white ascii art
            request.session["color"] = "white"
        else:
            print "uploading image failed"
    else:
        form = UploadImageForm() 
    return render(request, 'asciiart/success.html')

def index(request):
    return render(request, 'asciiart/index.html')

img_site/img_site/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
	return render(request, "img_site/index.html", {"message":"hello"})

img_site/asciiart/templates/asciiart/header.html
<!DOCTYPE html>
<html lang="en" style="background-color:#f6f6f6"> 
<head>
	<title>Welcome to Ascii Art</title>
	<meta charset="utf-8" />
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
	<link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="{% static 'font-awesome-4.6.3/css/font-awesome.min.css' %}" type="text/css" />
  <link rel="stylesheet" href="{% static 'css/app.css' %}" type="text/css" />
</head>
<body class="body">
	<div>
		{% block content %}
		{% endblock %}
	</div>

</body>
<script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
<script src="{% static 'js/bootstrap.file-input.js' %}"></script>
<script src="{% static 'js/typed.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
</html>

img_site/asciiart/templates/asciiart/index.html
{% extends "asciiart/header.html" %}

{% block content %}
<div class="centered"> 
  <span id="welcome"></span>
  <br><br>
  <form id="fileForm" name="form" enctype="multipart/form-data" action="{% url 'asciiart:process_image' %}" method="POST" >
        {% csrf_token %}
        {{ form.image }}
        <!-- Display filename inside the button instead of its label -->
        <input type="file" data-filename-placement="inside" name="file">
        <input type="submit" class="btn-default btn" value="Upload" disabled />
        <br>
        <br>
          <a  href="https://github.com/raphaellu/img-to-ascii">View on GitHub </a><i class="fa fa-github" aria-hidden="true" style="font-size:25px;"></i>
  </form>

</div>  

{% endblock %}

img_site/asciiart/templates/asciiart/success.html
{% extends "asciiart/header.html" %}

{% block content %}
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
  	<div class="navbar-header">
		<a href="/" class="navbar-brand" style="font-family:'Lato'"><i class="fa fa-arrow-left" aria-hidden="true"></i>&nbsp&nbspRestart</a>
  	</div>
  </div>
</nav>

<pre class="prettyprint"> 
	{{ request.session.display }}
</pre>
<div id="taiji"></div>      
{% endblock %}

img_site/img_site/templates/img_site/index.html
<html>
<head>
	

</head>
<body>
	<p>hihi</p>

</body>
</html>